### ISSUE TITLE
Error treating custom/tap/formula as a formula when there is a cask with the same name

### ISSUE THREAD

**Issue by cdalvaro** [Homebrew/homebrew-test-bot#1082]
I'm having the following issue with the _**Run brew test-bot --only-formulae**_ stage in my custom tap:

```
==> Running Formulae#formula!(cdalvaro/tap/salt)
==> brew deps --tree --annotate --include-build --include-test cdalvaro/tap/salt
==> Determining dependencies...
==> brew fetch --retry ::warning::Treating cdalvaro/tap/salt as a formula. For the cask, use cdalvaro/tap/salt or specify the `--cask` flag. asciidoc asciidoctor autoconf automake boost ca-certificates cmake docbook docbook-xsl gdbm gnu-getopt icu4c libgit2 libsodium libssh2 libtool libyaml llvm lz4 m4 mpdecimal ninja openssl@3 pcre2 pkg-config python@3.10 python@3.11 python@3.12 readline ruby rust six source-highlight sqlite swig xmlto xz z3 zeromq zstd
==> FAILED
Full fetch ::warning::Treating cdalvaro/tap/salt as a formula. For the cask, use cdalvaro/tap/salt or specify the `--cask` flag. asciidoc asciidoctor autoconf automake boost ca-certificates cmake docbook docbook-xsl gdbm gnu-getopt icu4c libgit2 libsodium libssh2 libtool libyaml llvm lz4 m4 mpdecimal ninja openssl@3 pcre2 pkg-config python@3.10 python@3.11 python@3.12 readline ruby rust six source-highlight sqlite swig xmlto xz z3 zeromq zstd output
  Error: No available formula or cask with the name "::warning::treating cdalvaro/tap/salt as a formula. for the cask, use cdalvaro/tap/salt or specify the `--cask` flag.".
  Please tap it and then try again: brew tap ::warning::treating cdalvaro/tap
  Error: No available formula or cask with the name "::warning::treating cdalvaro/tap/salt as a formula. for the cask, use cdalvaro/tap/salt or specify the `--cask` flag.".
  Please tap it and then try again: brew tap ::warning::treating cdalvaro/tap
```

I currently have a formula and a cask, both with the same name: `salt`.

Actions have been working fine until now.

These are my definitions:

- Formula: https://github.com/cdalvaro/homebrew-tap/blob/main/Formula/salt.rb
- Cask: https://github.com/cdalvaro/homebrew-tap/blob/main/Casks/salt.rb

And this is the PR that is currently failing: https://github.com/cdalvaro/homebrew-tap/pull/106

Am I doing something wrong?

Thank you for your help in advance!

**Comment by carlocab** [comment]
I think this is a bug in Homebrew/homebrew-test-bot. I've transferred your issue accordingly.

**Comment by MikeMcQuaid** [comment]
I suspect the issue is `conflicts_with cask: "cdalvaro/tap/salt"`. Try to remove that.

**Comment by MikeMcQuaid** [comment]
(note: if this is the problem: this should probably be a Homebrew/brew issue that should be fixed)

**Comment by cdalvaro** [comment]
> I suspect the issue is `conflicts_with cask: "cdalvaro/tap/salt"`. Try to remove that.

Thank you for the suggestion, @MikeMcQuaid! I've tried the formula removing the `conflicts_with` statement but the error persists:

```
==> Running Formulae#formula!(cdalvaro/tap/salt)
==> brew deps --tree --annotate --include-build --include-test cdalvaro/tap/salt
==> Determining dependencies...
==> brew fetch --retry ::warning::Treating cdalvaro/tap/salt as a formula. For the cask, use cdalvaro/tap/salt or specify the `--cask` flag. asciidoc asciidoctor autoconf automake boost ca-certificates cmake docbook docbook-xsl gdbm gnu-getopt icu4c libgit2 libsodium libssh2 libtool libyaml llvm lz4 m4 mpdecimal ninja openssl@3 pcre2 pkg-config python@3.10 python@3.11 python@3.12 readline ruby rust six source-highlight sqlite swig xmlto xz z3 zeromq zstd
==> FAILED
Full fetch ::warning::Treating cdalvaro/tap/salt as a formula. For the cask, use cdalvaro/tap/salt or specify the `--cask` flag. asciidoc asciidoctor autoconf automake boost ca-certificates cmake docbook docbook-xsl gdbm gnu-getopt icu4c libgit2 libsodium libssh2 libtool libyaml llvm lz4 m4 mpdecimal ninja openssl@3 pcre2 pkg-config python@3.10 python@3.11 python@3.12 readline ruby rust six source-highlight sqlite swig xmlto xz z3 zeromq zstd output
  Error: No available formula or cask with the name "::warning::treating cdalvaro/tap/salt as a formula. for the cask, use cdalvaro/tap/salt or specify the `--cask` flag.".
  Please tap it and then try again: brew tap ::warning::treating cdalvaro/tap
  Error: No available formula or cask with the name "::warning::treating cdalvaro/tap/salt as a formula. for the cask, use cdalvaro/tap/salt or specify the `--cask` flag.".
  Please tap it and then try again: brew tap ::warning::treating cdalvaro/tap
```

Apparently, nothing has changed from the previous log...

**Comment by MikeMcQuaid** [comment]
We'd review a PR adding `--formula` to the relevant `brew test-bot` calls.

**Comment by Bo98** [comment]
Might also be worth issuing those `::warning::` commands over stderr instead (assuming GitHub Actions supports that).

**Comment by carlocab** [comment]
This error message
```
Error: No available formula or cask with the name "::warning::treating cdalvaro/tap/salt as a formula. for the cask, use cdalvaro/tap/salt or specify the `--cask` flag.".
```
makes me think that the `::warning::` output that is meant for GHA is somehow being consumed by `test-bot` and being used as a formula argument for some reason.

Not sure how that's happening, but that seems to be the bug to me.

**Comment by Bo98** [comment]
> Not sure how that's happening, but that seems to be the bug to me.

yeah that's the `stdout` vs `stderr` thing I'm talking about. It currently outputs to `stdout` but should ideally be `stderr`

**Comment by Bo98** [comment]
> I'm not sure I agree with this; it's not the GitHub Actions output here that's the problem but the whole `opoo` output.

`opoo` prints to stderr:

https://github.com/Homebrew/brew/blob/cd651094878e88cb710bc24e253bff8b3595258e/Library/Homebrew/extend/kernel.rb#L67

but our annotation currently doesn't:

https://github.com/Homebrew/brew/blob/cd651094878e88cb710bc24e253bff8b3595258e/Library/Homebrew/utils/github/actions.rb#L54

Ideally they should print to the same place IMO.

**Comment by carlocab** [comment]
I've opened #1083 to fix this particular problem. It doesn't fix everything discussed above, however.

**Comment by carlocab** [comment]
> > yeah that's the `stdout` vs `stderr` thing I'm talking about. It currently outputs to `stdout` but should ideally be `stderr`
> 
> I'm not sure I agree with this; it's not the GitHub Actions output here that's the problem but the whole `opoo` output.

Funnily enough, I agree with both of you.

I agree that this particular `opoo` output is useless, and shouldn't be printed. That should be fixed by #1083, I think.

However, I also agree with @Bo98 that the `::warning::` output that comes out of `opoo` (in general, and not the particular one mentioned in this issue) should probably go to stderror if possible.

**Comment by cdalvaro** [comment]
My PR https://github.com/cdalvaro/homebrew-tap/pull/106 has been merged after the pipeline ended successfully!

So this patch has fixed my issue.

Thank you all of you!

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words @cdalvaro, sponsorship and great issue!
